version: '3.6'
services:
  web:
    env_file:
      - ./.env
    build:
      context: ./
      dockerfile: web.Dockerfile
    volumes:
      - "${WWW_VOLUME}:/var/www/html"
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 80:80
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    volumes:
      - "${MYSQL_VOLUME}:/var/lib/mysql"
    environment:
      TZ: Europe/Moscow
      MYSQL_ROOT_PASSWORD: mesh-task
      MYSQL_DATABASE: mesh-task
      MYSQL_USER: mesh-task
      MYSQL_PASSWORD: mesh-task
